# Site settings
title: Nomadas
header-img: img/home-bg.jpg
email: nomadas.ve@gmail.com
description: "Nomadas de la nueva era digital, ciudadanos del mundo, ávidos de conocer otras cultura"
baseurl: ""
url: "http://nomadas.com.ve"
twitter_username: NomadasVe
github_username:  elyalvarado
facebook_username:  NomadasVe
askfm_username: NomadasVe

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
